const assert = require('assert');
const fs = require('fs');

const js = fs.readFileSync('ui/ai-exe.js', 'utf8');
const html = fs.readFileSync('ui/ai-exe.html', 'utf8');
const css = fs.readFileSync('ui/ai-exe.css', 'utf8');
const mac = fs.readFileSync('src/gui_main_mac_web.mm', 'utf8');
const win = fs.readFileSync('src/gui_main_win_webview.cpp', 'utf8');
const winResources = fs.readFileSync('src/app.rc', 'utf8');
const plist = fs.readFileSync('src/Info.plist.in', 'utf8');

assert.ok(js.includes("const pendingPanel = pending.length ?"), 'pending panel must render only when actionable');
assert.ok(js.includes('function warmFinanceDashboardOnStartup(attempt = 0)'), 'finance must warm before its tab opens');
assert.ok(js.includes('setTimeout(() => { void warmFinanceDashboardOnStartup(); }, 350)'), 'startup must begin finance preload early');
assert.ok(js.includes('if (financeDashboardLoadPromise) return financeDashboardLoadPromise'), 'parallel finance loads must share one request');
assert.ok(js.includes('await renderBrokerPanel(currency)'), 'startup preload must include paper portfolio and market stream setup');
assert.ok(js.includes("const positionsPanel = positions.length ?"), 'empty positions panel must stay hidden');
assert.ok(js.includes("const historyPanel = history.length ?"), 'empty order history must stay hidden');
assert.ok(!js.includes('Nothing awaiting confirmation'), 'passive confirmation placeholder must be removed');
assert.ok(html.includes('id="dictationTimer"'), 'dictation timer must be present');
assert.ok(!html.includes('dictation-plus-ghost'), 'bottom recorder must not keep a decorative plus control');
assert.ok(html.indexOf('id="dictationCancelBtn"') < html.indexOf('id="dictationWave"'), 'cancel must lead the bottom recorder row');
assert.ok(js.includes('function startDictationTimer()'), 'dictation timer must start with recording');
assert.ok(js.includes('dictationWaveNoiseFloor + 0.010'), 'waveform must adapt its gate to the current room noise');
assert.ok(js.includes('Math.max(0.020, dictationWaveNoiseFloor + 0.010)'), 'waveform must retain a whisper-sensitive minimum gate');
assert.ok(js.includes('const envelopeMix = gatedTarget > dictationWaveEnvelope ? 0.82 : 0.28'), 'waveform must attack faster than it releases');
assert.ok(js.includes('const sampleIntervalMs = 150'), 'waveform must advance at the deliberate half-speed cadence');
assert.ok(js.includes('const barStepCss = 6.5'), 'waveform marks must use the tighter reference spacing');
assert.ok(js.includes('const flowOffset = sampleProgress * step'), 'waveform must flow continuously between audio samples');
assert.ok(js.includes('const displayHistory = [...dictationWaveHistory, amplitude]'), 'waveform must draw the live sample entering from the right');
assert.ok(!js.includes('Array.from({ length: samples }'), 'waveform history must slide instead of compressing over time');
assert.ok(js.includes('const historyStartX = w - ((displayHistory.length - 1) * step) - flowOffset'), 'waveform history must move by a smooth sub-step offset');
assert.ok(js.includes('dictationWaveHistory = Array(samples).fill(0)'), 'waveform row must start filled with quiet baseline samples');
assert.ok(!js.includes('dictationWaveFallbackPhase'), 'silence must not use fake waveform movement');
assert.ok(css.includes('.dictation-time'), 'dictation timer styling must be present');
assert.ok(css.includes('.dictation-bar {') && css.includes('order: 2;'), 'recorder must sit below the visible input text');
assert.ok(!css.includes('.input-row.dictation-active .input-text-line,'), 'recording must keep the input text visible');
assert.ok(mac.includes('GetOfflineDictationLevelOnMac'), 'Mac must expose real microphone level');
assert.ok(mac.includes('UpdateDictationTranscriptSegments'), 'Mac must accumulate timestamped speech segments across pauses');
assert.ok(mac.includes('transcript_segments.push_back'), 'Mac must preserve earlier recognition segments');
assert.ok(mac.includes('CommitCurrentDictationPhrase(cb)'), 'Mac must commit each completed phrase before continuing');
assert.ok(mac.includes('StartDictationRecognitionTaskLocked(cb)'), 'Mac must restart recognition after a pause-finalized phrase');
assert.ok(mac.includes('st.active = false;\n    if (st.request)'), 'Mac finalization must stop phrase rollover before ending audio');
assert.ok(!mac.includes('cb.best_text =\n                           std::string([result.bestTranscription'), 'Mac must not replace the full transcript with the newest partial phrase');
assert.ok(mac.includes('st.level_rms * 3.6'), 'Mac waveform gain must expose quiet speech to the adaptive gate');
assert.ok(js.includes("ctx.lineCap = 'round'"), 'active waveform bars must use smooth rounded ends');
assert.ok(js.includes('ctx.arc(centerX, centerY, dotRadius'), 'quiet waveform samples must render as evenly spaced round dots');
assert.ok(mac.includes('AcquireGuiInstanceLock'), 'Mac must reject duplicate GUI instances');
assert.ok(mac.includes('com.aiexe.desktop.show-main-window'), 'a second Mac launch must reveal the existing window');
assert.ok(mac.includes('AI exe logo white'), 'Mac tray must load the monochrome AI.EXE asset');
assert.ok(mac.includes('setTemplate:(statusIconPath != nil)'), 'Mac tray icon must follow menu-bar contrast');
assert.ok(mac.includes('for (int attempt = 0; attempt < 5; ++attempt)'), 'Mac launchd bootstrap must retry after removal races');
assert.ok(mac.includes('attempt * 150000'), 'Mac launchd retry must use bounded backoff');
assert.ok(mac.includes('bool WaitForLaunchdJobRemoval(NSString *target)'), 'Mac background transitions must wait for launchd removal');
assert.ok(mac.includes('attempt < 160'), 'Mac launchd barrier must outlast the five-second service exit window');
assert.ok(mac.includes('if (!WaitForLaunchdJobRemoval(target))'), 'Mac disable and enable paths must use the launchd barrier');
assert.ok(mac.includes('return RunLaunchctl(@[@"print", target], false, nullptr);'), 'Mac background state must reflect the registered launchd job');
assert.ok(mac.includes("typeof stopBrokerLiveUpdates === 'function'"), 'menu-bar quit must release the open market stream');
assert.ok(mac.includes('QOS_CLASS_USER_INITIATED'), 'menu-bar launchd shutdown must not block the UI thread');
assert.ok(js.includes("backgroundStatus.classList.toggle('error', isError)"), 'background service failures must have a distinct error state');
const backgroundToggleStart = js.indexOf("backgroundToggle.addEventListener('change'");
const backgroundToggleHandler = js.slice(
  backgroundToggleStart,
  js.indexOf("nativeBridge.invoke('paperBackgroundService'", backgroundToggleStart),
);
assert.ok(backgroundToggleHandler.includes("setBackgroundStatus(enabled, enabled ? 'Starting background service…' : 'Stopping background service…');"), 'background transitions must announce the pending state');
assert.ok(backgroundToggleHandler.includes('stopBrokerLiveUpdates();'), 'background transitions must release the market WebSocket before launchd stops');
assert.ok(js.includes("startBrokerLiveUpdates(financeLiveCurrency, financeLiveSymbol)"), 'market streaming must resume after a background transition');
assert.ok(css.includes('.paper-background-status.error'), 'background service failures must render in red');
assert.ok(plist.includes('NSSpeechRecognitionUsageDescription'), 'Mac bundle must declare speech recognition usage');
assert.ok(plist.includes('NSMicrophoneUsageDescription'), 'Mac bundle must declare microphone usage');
assert.ok(win.includes('SpeechRecognizer'), 'Windows must keep native speech recognition');
assert.ok(win.includes('kSingleInstanceMutex'), 'Windows must reject duplicate GUI instances');
assert.ok(win.includes('SystemUsesLightTheme'), 'Windows tray icon must follow the taskbar theme');
assert.ok(win.includes('RefreshPaperTrayIconTheme'), 'Windows tray icon must refresh after a theme change');
assert.ok(winResources.includes('2 ICON "status-icon-light.ico"'), 'Windows light-theme tray icon must be embedded');
assert.ok(winResources.includes('3 ICON "status-icon-dark.ico"'), 'Windows dark-theme tray icon must be embedded');
assert.ok(js.includes("document.documentElement.classList.contains('platform-windows')"), 'Windows must use its live WebAudio waveform path');

console.log('adaptive finance + dictation static test: ok');
