const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
global.window=global;require('../ui/agent-loop.js');
const loop=AIExeAgentLoop,norm=p=>'/'+String(p).replace(/^\/?/,'');
for(const p of ['/prisma/schema.prisma','/src/app/[username]/page.tsx','/src/app/api/auth/[...nextauth]/route.ts'])assert.deepEqual(loop.extractFileLikeTaskPaths(p,norm),[p]);
const events=[{tool:'write_file',ok:true},{tool:'run_app',ok:true,runErrorCount:1}];
assert.equal(loop.hasRuntimeAttemptSinceMutation(events),true);
for(let i=0;i<20;i++)assert.equal(loop.hasRuntimeAttemptSinceMutation([...events,{tool:'read_file',ok:true}]),true);
assert.equal(loop.hasRuntimeAttemptSinceMutation([...events,{tool:'write_files',ok:true}]),false);
assert.equal(loop.hasRuntimeAttemptSinceMutation([...events,{tool:'run_command',ok:true}]),false);
const executor=fs.readFileSync('ui/agent-executor.js','utf8'),ctx={};vm.createContext(ctx);
vm.runInContext(executor.match(/    function looksLikeMissingNodeDependencies\([^]*?\n    }/)[0],ctx);
assert.equal(ctx.looksLikeMissingNodeDependencies('sh: next: command not found'),true);
assert.equal(ctx.looksLikeMissingNodeDependencies('sh: vite: command not found'),true);
assert.equal(ctx.looksLikeMissingNodeDependencies('ENOENT: missing src/app/page.tsx'),false);
assert.equal(ctx.looksLikeMissingNodeDependencies('missing script: build'),false);
const core=fs.readFileSync('ui/agent-core.js','utf8');const c={normalizeWorkspacePath:norm};vm.createContext(c);
for(const f of ['extractPlannedPathFromPhaseTask','phaseTaskForPath','normalizeWebProjectPhases'])vm.runInContext(core.match(new RegExp('    function '+f+'\\([^]*?\\n    }'))[0],c);
const phases=c.normalizeWebProjectPhases([{title:'Auth',tasks:['src/app/login/page.tsx']},{title:'Profile',tasks:['src/app/[username]/page.tsx']}],['/package.json','/src/app/page.tsx','/src/app/login/page.tsx','/src/app/[username]/page.tsx'],'web');
assert.equal(phases.length,2);assert.ok(phases[0].tasks.some(t=>t.text==='src/app/login/page.tsx'));assert.equal(phases[1].tasks[0].text,'src/app/[username]/page.tsx');
console.log('PASS: failed proof not forced again without changes, missing Next install detected, dynamic routes and Prisma retained in original phases');
const planner=fs.readFileSync('ui/agent-planner.js','utf8');
const pc={buildAgentTaskRequirements:()=>[{met:false,label:'inspect /unrelated.config.js'}],effectiveAgentMaxSteps:()=>38};vm.createContext(pc);
vm.runInContext(planner.match(/    function buildImmediateNextAction\([^]*?\n    }/)[0],pc);
const directive=pc.buildImmediateNextAction('Fix build',[{tool:'run_command',ok:true,runErrorCount:1}],{},5);
assert.ok(directive.includes('latest terminal check failed'));
assert.ok(!directive.includes('NOW: inspect'));
console.log('PASS: compiler failure takes priority over unrelated planned inspection');
