const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const src=fs.readFileSync('ui/ai-exe.js','utf8');
const chats={a:{canvasMode:true,agentMode:true,thinkMode:true,webSearch:true},b:{canvasMode:false,agentMode:false,thinkMode:false,webSearch:false}};
const ctx={findChatById:id=>chats[id],activeChatId:'a',activeInferenceRequest:null,canvasModeEnabled:true,developerAgentEnabled:true,thinkModeEnabled:true,webSearchEnabled:true};
vm.createContext(ctx);
for(const fn of ['captureChatModes','inferenceModes'])vm.runInContext(src.match(new RegExp('^function '+fn+'\\([^]*?^}','m'))[0],ctx);
const queued=ctx.captureChatModes('b');
ctx.activeChatId='a';ctx.activeInferenceRequest={modes:queued};
assert.deepEqual(JSON.parse(JSON.stringify(ctx.inferenceModes())),{canvas:false,agent:false,think:false,search:false});
chats.b.thinkMode=true;
assert.equal(ctx.inferenceModes().think,false);
ctx.activeInferenceRequest={modes:ctx.captureChatModes('a')};ctx.activeChatId='b';
assert.equal(ctx.inferenceModes().agent,true);
assert.ok(src.includes('modes: captureChatModes(chat.id)'));
assert.ok(!src.includes('Boolean((targetChat && targetChat.canvasMode) || canvasModeEnabled)'));
const confirm=src.slice(src.indexOf('function renderComposerConfirmationUi('),src.indexOf('function renderComposerConfirmationUi(')+5500);
assert.ok(!confirm.includes('composer-confirm-actions-inline'));
const css=fs.readFileSync('ui/ai-exe.css','utf8');
assert.match(css,/\.composer-confirm-keycap.enter\s*\{[^}]*color: inherit;/);
console.log('PASS: queued modes frozen per request, background mode independence, separate confirmation actions and visible Return icon');
